services:
  master:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: test123*
    networks:
      - database
    ports:
      - "3307:3306"
  slave:
    image: mariadb
    ports:
      - "3308:3306"
    environment:
      MARIADB_ROOT_PASSWORD: test123*
    networks:
      - database

networks:
  database: